name: elp3rr0
favicon: null
layout_spectrum: 0.7404467579908669
typography_spectrum: 0.09209757577627897
title: this is the title
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9084087293595076
  lightness: 0.24608947499655187
  saturation: 0.8455625558272004
  rhythmicContrast: 0.8135736116673797
purpose: []
